### ISSUE TITLE
建议添加可限定文件类型拷贝

### ISSUE THREAD

**Issue by WhaleFell** [WhitemuTeam/USBCopyer#2]
可以用递归遍历u盘目录，筛选出 .docx .pptx .xls 文档的文件分类拷贝，不必把整个盘都copy下来。
另，可以使用shutil.copy()模块进行拷贝，避免用bat重复造轮子，也增强了兼容性，不弹出cmd黑框框。
提几个扩展性的建议：
1. 可以用win32py把Python脚本以服务的形式运行，设置开机自启动。
2. 可以尝试使用多线程threading拷贝。
3. 可以支持文件自动通过webdev同步到坚果云。
（睡不着瞄了眼Github。）

**Comment by Moemu** [comment]
抱歉，因为最近在搞没怎么更新Github，去搞[一个比赛程序](https://muspace.top/posts/54564/#第一次参加中小学生计算机制作大赛的决定)去了。你的建议不错，我看我等下写完年终总结之后能不能抽点时间来搞定。
首先是"递归遍历u盘目录"，因为老师U盘里面还有其他的东西是我比较感兴趣的，不一定是上面列出的所有格式，于是采用全盘复制的方式全盘复制，当然日后也打算加入自定义后缀名复制功能。
然后是开机自启问题。因为Seewo的非系统盘空间只有40G，拷比较大老师的U盘时总会满，而且避免重复拷贝，于是就没有考虑到开机自启功能。当然配合上上面的”自定义后缀名复制功能“也不错，再加个比较文件内容的插件就更好了。
多线程问题：使用多线程可能会导致老师放PPT时异常卡顿，建议看一下cmd弹出后系统运行速度即可。
云端同步问题：总体上是不错的，当然使用U盘直接复制也不错。但可以试一下使用WebDev同步到云端。
感谢您的建议~

**Comment by Moemu** [comment]
总体TO-DO如下：

- [x] 更改复制策略
- [x] 增加设置页面以设置更多功能
- [x] 增加开机自启功能（基于注册表而非服务，因为从服务启动程序存在问题）

**Comment by Moemu** [comment]
最后更新如下：
考虑到实际情况，不考虑云端同步，多线程
更新使用通过注册表设置开机自启动与更换更新策略
